import{a as q,S as v,i as M}from"./assets/vendor-GN5hr8qZ.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const E="52851423-7ef01ff8a01731751e4011988",u=15;async function f(r,a=1){const{data:t}=await q("https://pixabay.com/api/",{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:u}});return t}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),c=document.querySelector(".js-load-more"),$=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const a=r.map(({webformatURL:t,largeImageURL:s,tags:e,likes:o,views:i,comments:S,downloads:P})=>`
    <a class="card" href="${s}">
    <img src="${t}" alt="${e}" loading="lazy" width="360" height="200" />
    <ul class="meta">
    <li><b>Likes</b> ${o}</li>
    <li><b>Views</b> ${i}</li>
    <li><b>Comments</b> ${S}</li>
    <li><b>Downloads</b> ${P}</li>
    </ul>
      </a>
    `).join("");h.insertAdjacentHTML("beforeend",a),$.refresh()}function B(){h.innerHTML=""}function y(){m.classList.remove("is-hidden")}function p(){m.classList.add("is-hidden")}function O(){c.classList.replace("is-hidden","js-load-more")}function d(){c.classList.replace("js-load-more","is-hidden")}const b=document.querySelector(".form");let n=1,L="",w=0;b.addEventListener("submit",j);c.addEventListener("click",x);async function j(r){r.preventDefault();const a=r.target.elements["search-text"].value.trim();if(!a){l("Please enter a search term.");return}L=a,n=1,y(),d(),B();try{const t=await f(a,n);if(t.hits.length===0){d(),l("Sorry, there are no images matching your search query. Please try again!");return}w=t.totalHits,g(t.hits),t.hits.length<t.totalHits?O():d()}catch(t){l(t.message||"Something went wrong. Please try again.")}finally{p(),b.reset()}}async function x(){n++,c.disabled=!0,y();try{const r=await f(L,n);g(r.hits),n*u>=w&&(d(),l("We're sorry, but you've reached the end of search results."));const s=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"})}catch(r){l(r.message||"Something went wrong. Please try again.")}finally{p(),c.disabled=!1}}function l(r){return M.show({message:r,position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB"})}
//# sourceMappingURL=index.js.map
